spring:
  cloud:
    gcp:
      project-id: ${GOOGLE_PROJECT_ID}
      credentials:
        location: ${GOOGLE_CREDENTIALS}

  data:
    mongodb:
      uri: ${MONGODB_URI}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP}
    consumer:
      group-id: video-ingestion-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      auto-create-topics: true
    topics:
      video_ingested:
        partitions: 3
        replication-factor: 1

google:
  cloud:
    project-id: ${GOOGLE_PROJECT_ID}
    transcoder:
      location: us-central1
    credentials:
      file: ${GOOGLE_CREDENTIALS}

server:
  port: 8085
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB

logging:
  level:
    org.apache.kafka: DEBUG
